### ISSUE TITLE
Update metadata schema to address the following point

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/metadata-schemas#20]
1. metadata fields needs to be consistently and determinately ordered in the schema
2. styling information needs to be added/adjusted for ISSN fields (@jabrah please add more details here before @birkland can implement this)

**Comment by birkland** [comment]
The ordering of JSON object fields is technically undefined.  So maybe it's best to leverage Alpaca feature(s) to specify order:
http://www.alpacajs.org/docs/api/ordering.html

The `order` field looks tempting, but that particular page is useless, as does nothing to describe the `order` field in terms of where that field should appear, and what value(s) it should contain.

**Comment by birkland** [comment]
@jabrah I found "[documentation](https://github.com/musicist288/alpaca/commit/e58a03712566c1e44b402b705f044d9dbdf7475d#commitcomment-11935518)" for an `order` property.  Does this actually work?  If so, we can amend the schemas to add order properties.

**Comment by jabrah** [comment]
I'll check out the `order` property.

There are a small handful of other changes that need to be made to the schemas, which I will put here when ready.
