### ISSUE TITLE
Update schema to include $schema

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/metadata-schemas#23]
- [x] update schemas document
- [x] update relevant documentation 
- [x] cut a release and create new schema service image that reflect this change

**Comment by birkland** [comment]
The metadata blob should reference the schema it complies with, adding a `$schema` field will make the blob unambiguous

**Comment by birkland** [comment]
This was complete as of https://github.com/OA-PASS/metadata-schemas/releases/tag/v0.2.0
