### ISSUE TITLE
Update Ember image to add an environment variable to point to the schema service

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/metadata-schemas#9]
more context here https://docs.google.com/document/d/1Ki6HUYsEkKPduungp5gHmr7T_YrQUiaTipjorcSnf4s/edit#

@birkland what the blockers for this ticket, as far as the ember codebase's readiness?

**Comment by jabrah** [comment]
This change is part of the mega-PR that is currently ongoing:
https://github.com/OA-PASS/pass-ember/pull/878/files#diff-afbf2db75d44d2d47a0ba4e55aab0913R65

The Ember env is then updated:
https://github.com/OA-PASS/pass-ember/pull/878/files#diff-695693c5dabaffb064bde5b060195ff7R93
